(define list1 (list "a" "b" "c" "d" "a" "c" "a" "a"))
(define list2 (list "c" "c" "b" "e" "e" "e" "e" "a"))
(define list3 (list "a" "a" "b" "b" "b" "c" "b" "a" "b" "e"))
(define list4 (list "e" "e" "e" "e" ))
(define list5 (list " "))
(define list6 (list "d" "a" "b" "d" "c" "c" "d" "e" "e"))
(define list7 (list "a" "b" "c" "e" ))
(define list8 (list 92 92 92 92 1))
(define list9 (list "a" "d" "e" 6 8 "e" "c" 3 6 291))
(define list10 (list 99 99 99 1 99 99 1))

(define (findAndReplace x y lst)
  (cond ((null? lst) '()) 
        ((list? (car lst)) (cons (findAndReplace x y (car lst)) (findAndReplace x y (cdr lst)))) 
        ((eq? (car lst) x) (cons y (findAndReplace x y (cdr lst))))
        (else
         (cons (car lst) (findAndReplace x y (cdr lst))))))

(findAndReplace "a" "c" list1)
(findAndReplace "e" "f" list2)
(findAndReplace "b" "a" list3)
(findAndReplace "e" "b" list4)
(findAndReplace " " "c" list5)
(findAndReplace "d" "ahhhh" list6)
(findAndReplace "b" "k" list7)
(findAndReplace 1 92 list8)
(findAndReplace "e" 6 list9)
(findAndReplace 99  1 list10)
